__app__/match_company/company_domain_match_list.yaml
Thank you for this lovely project!
This pull requests adds Bjerk to the list. Bjerk is a development agency in Oslo, Norway. We contribute quite a lot to FOSS, it is a part of the core values of our company.
=> Add Bjerk to company list

README.md, requirements.txt
I needed to install pypandoc to get pyspark to work. The README edits were small notes as I tried installing it.
=> Adding pypandoc as peerDep and slight edits to README

__app__/match_company/company_domain_match_list.yaml
=> Add Expedia Group to list.

__app__/match_company/company_domain_match_list.yaml
=> Add a new open source company: StreamNative

__app__/match_company/company_domain_match_list.yaml
=> Add Akvelon to the companies list

__app__/match_company/company_domain_match_list.yaml
Hi, 
I am a community manager at Linagora which is a French open-source software company. I noticed that it was missing from the list of companies. 
Request to merge this PR.
=> Adding a new company: Linagora

__app__/match_company/company_domain_match_list.yaml
[LINE Corporation](https://linecorp.com) ❤️ [Open Source](https://github.com/line)
=> Add LINE Corporation

__app__/match_company/company_domain_match_list.yaml
=> Add Société Générale

osci/preprocess/match_company/company_domain_match_list.yaml
Replacement of #85 
Signed-off-by: Jeroen Knoops <jeroen.knoops@philips.com>
=> Add philips.com

osci/preprocess/match_company/company_domain_match_list.yaml
Our team filled in the industry parameter for each company. We ask for validation from the community of people who added companies to our list:
@devashish-gaikwad please check Société Générale https://github.com/epam/OSCI/blob/305e4ce2062118ddcb13da0843916ad0c6fe24db/osci/preprocess/match_company/company_domain_match_list.yaml#L1396-L1400
@JeroenKnoops please check Philips https://github.com/epam/OSCI/blob/305e4ce2062118ddcb13da0843916ad0c6fe24db/osci/preprocess/match_company/company_domain_match_list.yaml#L1158-L1162
@mmorozkov please check Devexperts https://github.com/epam/OSCI/blob/305e4ce2062118ddcb13da0843916ad0c6fe24db/osci/preprocess/match_company/company_domain_match_list.yaml#L423-L427
@hfukuchi please check Sony https://github.com/epam/OSCI/blob/305e4ce2062118ddcb13da0843916ad0c …
=> Filling in the industries parameter for companies

osci/preprocess/match_company/company_domain_match_list.yaml
See https://smartbear.com/company/about-us/
We have a lot of different domains through acquisitions.
=> Add SmartBear to list of companies

osci/preprocess/match_company/company_domain_match_list.yaml
[Siemens :heart: Open Source](https://opensource.siemens.com), so we should definitely be on this list 😀
=> Add Siemens

osci/preprocess/match_company/company_domain_match_list.yaml
Hello 👋🏾 
As part of a recent acquisition https://pactflow.io/blog/pactflow-joins-the-smartbear-family/
Thanks!
=> chore: add pactflow.io domain under SmartBear company

osci/preprocess/match_company/company_domain_match_list.yaml
Add Aiven to the list of corporations
=> Add Aiven to the list

osci/preprocess/match_company/company_domain_match_list.yaml
Company website: https://lablup.com
Main product website: https://backend.ai
=> Add Lablup to the company list

osci/preprocess/match_company/company_domain_match_list.yaml
- Add FARFETCH (farfetch.com) to the company list
=> Add FARFETCH to the company list

osci/preprocess/match_company/company_domain_match_list.yaml
- Add Intesys (intesys.it) to company list
Company website: https://www.intesys.it
About our support to open source projects:
- [Open hospital](https://www.open-hospital.org/) 
- https://github.com/informatici/openhospital-ui;
- https://github.com/intesys/openhospital-core;
- https://github.com/intesys/openhospital-api
- More about ongoing OS projects: https://github.com/intesys
=> Add Intesys to the company list

osci/preprocess/match_company/company_domain_match_list.yaml
Update Aiven domains and email regex. Add klaw-project.io
=> Update Aiven domains and email regex

osci/preprocess/match_company/company_domain_match_list.yaml
Company website: https://layer5.io/
=> Add Layer5 to the company list

osci/preprocess/match_company/company_domain_match_list.yaml
* Add Fujitsu to the company list
=> Add Fujitsu to the company list

osci/preprocess/match_company/company_domain_match_list.yaml
Update Companies list:
- Update Yandex #159
- Add Layer5 #158  
- Add Spotify #156 
- Add AE Studio #155 
- Update & fix companies names and industries #154 
- Add Fujitsu #153
=> Release v2023.03.0

osci/preprocess/match_company/company_domain_match_list.yaml
Adding additional domain names on behalf of Optum's Open Source Program Office for proper tracking of public commits.
=> Adding additional domains for Optum associates

osci/preprocess/match_company/company_domain_match_list.yaml
=> Adding JPMC to OSCI

osci/preprocess/match_company/company_domain_match_list.yaml
Community,
thank you for maintaining and operating the Open Source Contributor Index. This is a valuable overview we'd like to be part of.
The proposed PR adds Porsche and its subsidiaries to the company domain match list. The regex should cover most of the domains we use to contribute to open-source projects.
Best regards,
Eduard from the Porsche AG Open Source Office
=> List Porsche and subsidiaries on OSCI

osci/preprocess/match_company/company_domain_match_list.yaml
=> Add company DoliCloud

osci/preprocess/match_company/company_domain_match_list.yaml
This PR adds @10up to the OSCI index of matched companies.
=> Add 10up to OSCI

osci/preprocess/match_company/company_domain_match_list.yaml
=> Fix databricks description

osci/preprocess/match_company/company_domain_match_list.yaml
I am a member of the Schenker Open Source Program Office. We decided to add DB Schenker to the index. Thanks!
=> Add DB Schenker

osci/preprocess/match_company/company_domain_match_list.yaml
Signed-off-by: Mark Matyas <mmatyas@quic.qualcomm.com>
=> Add additional QuIC e-mail domain

osci/preprocess/match_company/company_domain_match_list.yaml
This pull requests adds Mercedes-Benz Group AG to the company list
<sup>Alexander Mohr, <alexander.m.mohr@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [imprint](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)</sup>
=> Add Mercedes-Benz Group AG to the company list

osci/preprocess/match_company/company_domain_match_list.yaml
Adding the TYPO3 project (company and association) with both main domains.
=> Adding TYPO3 to company_domain_match_list.yaml
